name: Click

on:
  repository_dispatch:
    types: ["click"]

jobs:
  click:
    runs-on: ubuntu-latest

    steps:
      - name: Click on element
        run: |
          curl -X POST "https://proxy-1-2d08.onrender.com/click" \
          -H "Content-Type: application/json" \
          -d '{"locator":"${{ github.event.client_payload.locator }}"}'