name: Close Browser

on:
  repository_dispatch:
    types: ["close"]

jobs:
  close:
    runs-on: ubuntu-latest

    steps:
      - name: Close Browser
        run: |
          curl -X GET "https://proxy-1-2d08.onrender.com/close"