name: Open URL

on:
  repository_dispatch:
    types: ["open"]

jobs:
  open:
    runs-on: ubuntu-latest

    steps:
      - name: Open URL
        run: |
          curl -X POST "https://proxy-1-2d08.onrender.com/open" \
          -H "Content-Type: application/json" \
          -d '{"url":"${{ github.event.client_payload.url }}"}'